// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf2OHrZkJ4c_INKVFjnUmk479AhQoOx94',
    appId: '1:351020799516:web:1945b785065019cd90b1d9',
    messagingSenderId: '351020799516',
    projectId: 'hair-designer-sales-manage',
    authDomain: 'hair-designer-sales-manage.firebaseapp.com',
    databaseURL: 'https://hair-designer-sales-manage-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hair-designer-sales-manage.appspot.com',
    measurementId: 'G-JQ7NQ1D0WH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWPkJ3y43Pz3HNkIS5zYRiF0l9nrlyYrE',
    appId: '1:351020799516:android:f90932a8d933f9be90b1d9',
    messagingSenderId: '351020799516',
    projectId: 'hair-designer-sales-manage',
    databaseURL: 'https://hair-designer-sales-manage-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hair-designer-sales-manage.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhiGgfLnJUKOVRNzrpc7IrdYnSUhn1g6Y',
    appId: '1:351020799516:ios:156fa3c0602d5f5490b1d9',
    messagingSenderId: '351020799516',
    projectId: 'hair-designer-sales-manage',
    databaseURL: 'https://hair-designer-sales-manage-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hair-designer-sales-manage.appspot.com',
    iosBundleId: 'com.example.hairDesignerSalesManage2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhiGgfLnJUKOVRNzrpc7IrdYnSUhn1g6Y',
    appId: '1:351020799516:ios:cc55ffbc3db6575690b1d9',
    messagingSenderId: '351020799516',
    projectId: 'hair-designer-sales-manage',
    databaseURL: 'https://hair-designer-sales-manage-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hair-designer-sales-manage.appspot.com',
    iosBundleId: 'com.example.hairDesignerSalesManage2.RunnerTests',
  );
}
